@include('admin.includes.head')
@include('admin.includes.header')
@include('admin.includes.sidebar')
@include('admin.includes.breadcrumb')
@yield('content')
@yield('scripts')
@include('admin.includes.script')